# Generated by Django 3.2.5 on 2021-07-23 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Tytul', models.CharField(default=True, max_length=200)),
                ('Tresc', models.TextField()),
                ('TekstPrzycisku', models.CharField(default=True, max_length=200)),
                ('Zdjecie', models.CharField(default=True, max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='SectionConfig',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Gdzie', models.BooleanField(default=True)),
                ('Kiedy', models.BooleanField(default=True)),
                ('Transport', models.BooleanField(default=False)),
                ('Kontakt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransportSection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Tytul', models.CharField(default=True, max_length=200)),
                ('Tresc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrzaskanieSection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Tytul', models.CharField(default=True, max_length=200)),
                ('Tresc', models.TextField()),
                ('Data', models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 0))),
                ('Zdjecie', models.CharField(default=True, max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='WhenSection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Tytul', models.CharField(default=True, max_length=200)),
                ('Tresc', models.TextField()),
                ('Data_Slubu', models.DateTimeField(default=datetime.datetime(2021, 8, 28, 11, 30))),
                ('Zdjecie', models.CharField(default=True, max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='WhereSection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Tytul', models.CharField(default=True, max_length=200)),
                ('Tresc', models.TextField()),
                ('TekstDodatkowy', models.TextField()),
                ('TekstPrzycisku', models.CharField(default=True, max_length=200)),
                ('Zdjecie', models.CharField(default=True, max_length=800)),
            ],
        ),
    ]
